### ISSUE TITLE
Add support for renaming a level

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#9] opened 2020-04-01 10:53 UTC
How can I rename a level ?

Something like that would be nice:

```python 
levels["old"].name = "new"
```

**Comment by fabiencelier** [comment] 2020-04-01 15:46
There is no API for that at the moment, you can only choose the name of the level when creating it:
```python
cube.hierarchies["myHier"] = { 'myLevel': storeA["myField"]}
```

**Comment by fabiencelier** [comment] 2020-04-02 15:49
Also is there a real use case for renaming the level instead of naming it correctly at the creation ?

I understand that it is convenient to change the name after creation but if it is just that it won't be a priority.

**Comment by rcolle** [comment] 2020-04-02 15:51
> Also is there a real use case for renaming the level instead of naming it correctly at the creation ?
> 
> I understand that it is convenient to change the name after creation but if it is just that it won't be a priority.

Moreover, all the code that was written using the previous level name (e.g. measure definition) won't make sense anymore. I'm much more in favor of naming the level correctly from the start.

**Comment by SamTaz** [comment] 2020-04-10 13:26
I use auto mode to create levels/measures and had the same issue when I wanted to rename a few measures.
Say you have a `stock` numerical column in your base store, Atoti will create `stock.SUM` and `stock.AVG` and I found no nice way to rename these to "Stock" and "Average stock", did I miss something or do we have a similar issue with measure names ?
Since I am working on a public Atoti notebook I don't want to use any dirty workaround such as `m["Stock"] = m["stock.SUM"]` then `del m["stock.SUM"]`.

I think also the philosophy of users here is a bit different from how we used to do activepivot projects.
Switching to manual mode or having nice names in file columns would lead people to stop what they are doing in the notebook, make their fixes (column name changes in files, right manual names for columns/measures), restart Atoti and re-run everything again: not the impossible but a bit cumbersome for simple renaming. 
In my case I just end up keeping the default measure names to avoid doing that.

**Comment by chamb** [comment] 2020-04-10 14:31
@SamTaz maybe you can create your cube in mode `"no_measures"` and create the measures yourself with the right name?

**Comment by rcolle** [comment] 2020-05-29 01:01
As @chamb proposed, @SamTaz 's use case is best solved with the `no_measures` mode. 
And the issue is about renaming levels, not measures ;)

Since there doesn't seem to be a use case for renaming a level, I will close this for now. 
Feel free to comment again if a use case arises.

**Closed by rcolle** 2020-05-29 01:01 UTC
Labels: enhancement :sparkles:
