### ISSUE TITLE
Error when using mode 'interpolate' of date_shift

### ISSUE THREAD

**Issue by lisaMartini** [atoti/atoti#189] opened 2020-11-26 13:54 UTC
## Steps to reproduce

 when using a combination of 2 measures one using scope.cumulative and the other using the date_shift with 'interpolate' mode as follow : 

```
 measures[cc.AGGREGATED_QUANTITIES_PER_W] = tt.agg.sum(
            measures[cc.SALES_QUANTITY],
            scope=tt.scope.cumulative(levels[cc.SALE_DATE], window=("-1W", None)),
        )
        measures[cc.AGGREGATED_QUANTITIES_PER_W_SHIFTED_BY_1W] = tt.date_shift(
            measures[cc.AGGREGATED_QUANTITIES_PER_W],
            on=hierarchies[cc.SALE_DATE],
            offset="-1W",
            method="interpolate",
        )
```

## Actual Result

I get an error within the UI which states : ** Index Array out of bound** when I display a hierarchy with all member. 
If I remove the allMember and display only members I get this : 
![image](https://user-images.githubusercontent.com/44759708/100358659-c5af6a80-2ff6-11eb-9fb1-4e38ee2e4e02.png)

If I change the mode of the date_shift to exact I don't have any issue

## Environment

- atoti-plus: 0.4.4.20201112155141
- Python: 3.7.8
- Operating System: windows

**Comment by fabiencelier** [comment] 2020-11-26 14:07
ArrayIndexOutOfBoundsException is the same as https://github.com/atoti/atoti/issues/112

The ClassCastException looks like a new error, it would be nice to have the full stack trace from the logs

**Comment by tibdex** [comment] 2021-01-28 16:35
Closing this for now because no reproduction steps were provided and part of the issue is fixed. If someone else encounters the same problem on a recent version, feel free to reopen.

**Closed by tibdex** 2021-01-28 16:35 UTC
Labels: bug :bug:
