### ISSUE TITLE
Need to restart notebook upon exception in measure creation

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#63] opened 2020-06-11 01:56 UTC
## Steps to reproduce
During measure creation, unable to run any cells once I encounter exceptions. I have to restart the kernel.  

Wrong level supplied to function:
`m["Worst VaR End Date"] = tt.agg.min_member(m["1d 99% VaR Sliding"], levels=l["Portfolio"])`
resulting in 
```
KeyError: 'Multiple levels named Portfolio. Use a tuple to specify the hierarchy:\n\tcube.levels[("Portfolio Structure","Portfolio")]\n\tcube.levels[("Portfolio","Portfolio")]'
```

![restart_required_upon_exception](https://user-images.githubusercontent.com/35210495/84335821-52d94100-abc8-11ea-8e72-792d1354af95.gif)

## Expected Result
I should be able to rectify the measure's definition without having to restart the kernel.

## Environment
- atoti: 0.4.0
- Python: 3.8.2
- Operating System: win32

**Comment by fabiencelier** [comment] 2020-06-11 08:23
Hello,

I have tried this exception and I have no issue running other cells. This exception happens on the Python side before modifying the session so it should not break anything.

I have tried the following:

```python
import atoti as tt
import pandas as pd
df = pd.DataFrame({"a": ["A", "B"], "b": [10.0, 20.0]})
session = tt.create_session()
store = session.read_pandas(df, store_name="test")
cube = session.create_cube(store)
m = cube.measures
h = cube.hierarchies
l = cube.levels
# create new hierarchy with same level:
h["c"] = [l["a"]]

# This raises a key error:
m["Worst VaR End Date"] = tt.agg.min_member(m["b.SUM"], level=l["a"])


# But this still works:
cube.visualize()

# I can still create the measure correctly:
m["Worst VaR End Date"] = tt.agg.min_member(m["b.SUM"], level=l["c", "a"])
```

**Comment by fabiencelier** [comment] 2020-07-02 14:25
Closing as I cannot reproduce, feel free to reopen with more details

**Closed by fabiencelier** 2020-07-02 14:25 UTC
Labels: bug :bug:
