### ISSUE TITLE
Labeling in Widget

### ISSUE THREAD

**Issue by ncosgrov** [atoti/atoti#103] opened 2020-07-14 18:25 UTC
## Description

I am going to apologize in advance if this is ignorance on my part.   My request is two-fold regarding labeling in the widget

1) That the user to be able to label with, the text of their choice, the x and y-axis where appropriate.

2) When dealing with a hierarchy, to be able to specify that the lowest level of the hierarchy be used for labeling the plots in the key

## Context

Point (1) I think is clear.  Point two is this scenario:  I have a hierarchy of userId and Fullname.  The hierarchy resolves the data issue that people may have identical names, but their userid is unique.  However, when I plot on that Hierarchy the data is labeled userid,Fullname which is messy and distracting.  I would like to have plot just labeled on the Fullname level and if there is redundancy speak to it.   Note the dataset I am using is large and is only comprehensible if filtered, the odds of a duplicate in a filtered range is small making the userid superfluous. 

Example below, x should be labeled "career year", h as "hits", would ideally like plot labeled "Dereck Jeter" not "jeterse01,Dereck Jeter"

## Other information (if relevant)
![Captains](https://user-images.githubusercontent.com/56321847/87461870-0759ee80-c5dd-11ea-8edc-795636bf097b.png)

**Comment by fabiencelier** [comment] 2020-07-15 08:38
Hello,
Thank you for reporting the issue !

Point 1 is related to https://github.com/atoti/atoti/issues/8 which asks for a way to display the axes (names of levels and measures)

**Comment by tibdex** [comment] 2020-08-13 10:12
Hello, for point 2, as you said, `User ID` is more specific than `Full name` so you could change the order of the hierarchy like that:

```python
h["User"] = [lvl["Full name"], lvl["User ID"]]
```

and pick the `Full name` level in your chart instead of `User ID`.

The risk would then be to aggregate multiple users with the same full names but different IDs under the same line but, not reordering the hierarchy and hiding the `User ID` from the caption could end up with multiple lines with the same `Full name` caption which would be confusing too.

**Comment by bloussou** [comment] 2022-01-27 16:35
I'm closing this as it is a duplicate of #8 for part 1 and a solution has been provided for part 2

**Closed by bloussou** 2022-01-27 16:35 UTC
Labels: :sparkles: enhancement, :lipstick: ui
