### ISSUE TITLE
Visualization shows different results when running cell by cell vs all cells 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#670] opened 2022-08-18 05:55 UTC
## Steps to reproduce

Refer to XVA notebook from the gallery: https://github.com/atoti/notebooks/blob/hfy/0.7.0/upgrade/notebooks/xva/main.ipynb

If I run all the cells in one go, the visualization returns on one member results.
However, if I execute up till the cell before, then execute the visualization after, the value changes.

![what-if-different-results](https://user-images.githubusercontent.com/35210495/185304470-7fdfcede-b6f0-47b7-b93f-14a18cd196ff.gif)

## Environment

- atoti: 0.7.0
- Operating system: win32
- Browser: Chrome

**Comment by Skyscimitar** [comment] 2022-08-18 08:30
I can reproduce the issue by running queries on the cube before and after running the last cell. This doesn't seem to be a UI related issue. I'll get back to you as I carry on the investigation.

**Comment by Skyscimitar** [comment] 2022-08-18 08:49
Okay found the problem, the `AsOfDate` hierarchy is slicing, when you don't run all the cells, there is only one `AsOfDate`: `2020-09-08` which is therefore the default value for the hierarchy. However when you run all the cells, since the widget doesn't block the notebook's execution the data from the previous date is loaded. This changes the default value for the `AsOfDate` hierarchy from `2020-09-08` to `2020-09-07` (the default value is the first value in the order of the comparator which is the natural order comparator by default). This explains why the result on the base scenario is different. Since you only load data into the `Base` scenario of the table, there is no data for the other scenarios with the new default date, therefore there is no data for the other scenarios whence they are not displayed in the widget.

**Comment by tibdex** [comment] 2022-08-23 20:52
Hi Hui Fang, I think the problem was there before 0.7.0 but it will be fixed in the next release.

**Closed** 2022-10-12 22:08 UTC
Labels: :bug: bug, :lipstick: ui
