### ISSUE TITLE
UI Bugs reporting with screen print throws exception

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#14] opened 2020-04-15 01:39 UTC
## Description
Trying to download error reports for UI with screenshot, I encounter another error that prevents the download. Please see screenshot attached.

## Reproduce
Check "Screenshot" in the options and click download:
![image](https://user-images.githubusercontent.com/35210495/79289703-9d0db100-7efc-11ea-8298-d52c443ccb4d.png)

## Context
- Atoti version: 0.3.1
- Browser: Chrome
- Operating System: Windows 10 Pro

**Comment by tibdex** [comment] 2020-04-15 14:30
I was able to reproduce on Chrome 80 and macOS 10.15.3. The report was generated but the screenshot in it was empty. I had these lines in the browser console:

<img width="1246" alt="Screenshot 2020-04-15 at 16 26 11" src="https://user-images.githubusercontent.com/6574550/79348877-ddd5ec00-7f35-11ea-9d2b-6021ef5afd4f.png">

Looks like the library [dom-to-image](https://www.npmjs.com/package/dom-to-image) used by ActiveUI SDK is having trouble capturing the complex DOM of JupyterLab.

A fix would be to have an option in the SDK to disable this "Screenshot" check box.

**Comment by tibdex** [comment] 2020-07-28 08:52
This won't be fixed until the next major version of ActiveUI. Next time you want to attach a screenshot, you can use your OS or browser to generate it instead of having ActiveUI do it.

**Closed by tibdex** 2020-07-28 08:52 UTC
Labels: bug :bug:, ui :bar_chart:, waiting dependency :hourglass_flowing_sand:
