### ISSUE TITLE
Misleading error message on stores involved in "Reference between two fields of different type"

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#82] opened 2020-06-24 10:25 UTC
## Steps to reproduce
Using the attached csv in [data.zip](https://github.com/atoti/atoti/files/4824714/data.zip)

```
competitorPrices = session.read_csv(
    "competitor_prices3.csv",
    keys=["ProductId", "CompetitorStoreId", "StoreId"],
    store_name="CompetitorPrices",
    sep=";",
    types={
        "ProductId": tt.types.INT,
        "StoreId": tt.types.INT,
        "CompetitorStoreId": tt.types.INT,
    }
)
```
![image](https://user-images.githubusercontent.com/35210495/85537754-d2debc80-b646-11ea-8c9b-2b1fddd0485b.png)

```
competitorStore = session.read_csv(
    "s3://data.atoti.io/notebooks/geopricing/competitor_stores.csv",
    sep=";",
    keys=["CompetitorStoreId"],
    store_name="CompetitorsStores",
)

competitorStore.head()

distance_matrix = session.read_pandas(
    "distance_matrix.csv",
    keys=["StoreId", "CompetitorStoreId"],
    store_name="DistanceMatrix",
)

competitorPrices.join(
    competitorStore, mapping={"CompetitorStoreId": "CompetitorStoreId"}
)
competitorPrices.join(
    distance_matrix,
    mapping={"CompetitorStoreId": "CompetitorStoreId", "StoreId": "StoreId"},
)
```

Error message thrown:
```
AtotiJavaException: The reference CompetitorPrices_to_CompetitorsStores is between two fields of different type. Field 'CompetitorStoreId' of store 'CompetitorPrices' is 'long' whereas field 'CompetitorStoreId' of store 'CompetitorsStores' is of type 'int'. Recommended action: Use the same type for both fields.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path
```

But in actual fact, it is not due to the type of CompetitorPrices but rather DistanceMatrix store:

![image](https://user-images.githubusercontent.com/35210495/85538298-55677c00-b647-11ea-823b-5b142673ecec.png)

The error message is misleading

## Environment

- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by fabiencelier** [comment] 2020-07-02 14:45
I have used `s3://data.atoti.io/notebooks/geopricing/competitor_outlets.csv` instead of  `s3://data.atoti.io/notebooks/geopricing/competitor_stores.csv` which does not exist anymore and I cannot reproduce the issue. All my fields are int and I don't have any long:
![schema](https://user-images.githubusercontent.com/17087544/86373129-5752c000-bc83-11ea-89c3-eaca1bfd4525.png)

If you still have this issue can you provide more details to reproduce it ?

**Comment by tibdex** [comment] 2021-02-01 15:18
Closing the issue because it couldn't be reproduced.

**Closed by tibdex** 2021-02-01 15:18 UTC
Labels: bug :bug:, join :link:
