### ISSUE TITLE
Issue with where condition True when it should not

### ISSUE THREAD

**Issue by SamTaz** [atoti/atoti#17] opened 2020-04-17 09:28 UTC
Hello,

I am working on a formula 1 dataset where data gives the championship standings at the end of each race. Trying to compute the championship winner for each year (so in theory driver with position == 1 at the end of the year) I am having trouble with a where statement that tests if a measure is equal to another.
It seems a where statement returns True in cases it is not supposed to. I am raising this issue after showing it to @fabiencelier 

I have a first measure giving the name of winner of a round (raceNr) for a particular year:
`m["First driver at round"] = tt.filter(m["Driver Name"], l["position"] == 1)`

Then to have it at year level, and since we cannot use measures in filters, the idea was to have a where statement returning None when the race is not the last of the season, and the previous measure otherwise. Then leaf evaluate this where statement at round level, and aggregate with single value since there should be only one non null value.

`m["1st in standings"] = tt.where(m["Nr of rounds until race"] == m["Nr of rounds in year"], m["First driver at round"], None)`

`m["Year Winner"] = tt.agg.single_value(m["1st in standings"], scope=tt.scope.origin("round"))`

First issue is that measure `m["1st in standings"] ` is always null (I cannot see it in a pivot table)
Second issue is that year winner is correctly computed for the last race of the season, but is also non null for some other races, even though `m["Nr of rounds until race"]` is *not* equal to `m["Nr of rounds in year"]`
See the result in the below picture:
![image](https://user-images.githubusercontent.com/39309622/79554371-3fb16580-809e-11ea-90a8-b97e0d2be77f.png)

Do you have any idea why ? 

[Find here a short notebook with the reproduction and indications](https://github.com/atoti/atoti/files/4492046/f1.issue.where.zip)

**Comment by rcolle** [comment] 2020-04-17 15:42
There seems to be several issues related to the inferred required levels:
- `tt.filter(...)` infers all the filtered levels as required levels. I'm not sure this is necessary, and removing it seems to fix the wrong results.
- `m["1st in standings"]` is always `null` because `m["First driver at round"]` requires the `driverId` level, and `where` adds a `per()` clause on all underlying required levels. It should probably only enforce the `per` on the required levels of the boolean condition(s).

@a-manai what do you think?

**Comment by rcolle** [comment] 2020-05-29 01:07
The wrong results have been fixed in 0.4.0, but the issue with `where` not returning a value still exists:
https://github.com/activeviam/atoti/blob/4b77a29ac79284b3e20d46ee8a8f1cce3dc91bde/java/patachou/core/src/main/java/com/activeviam/chouket/pivot/alambyk/impl/AlambykBuilder.java#L1367

Assigning this to @a-manai

**Comment by a-manai** [comment] 2020-06-22 12:25
Hello,

This issue was caused by the `where` measure propagating more restrictions than needed on the required levels (the levels for which it has non-null values).
The next release will contain the bug fix.

Cheers

**Closed** 2020-07-16 09:45 UTC
Labels: bug :bug:
