### ISSUE TITLE
Unable to find member to be added to filter

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#216] opened 2021-01-18 08:34 UTC
## Steps to reproduce

There are about 19,646 rows of Player data. In pivot table, I could retrieve up to alphabet Z.
However, in the search list, I could only reach alphabet J and I couldn't even use the search box to select the intended player.
How can I add the filtered member?

![image](https://user-images.githubusercontent.com/35210495/104890667-d6eb7680-59aa-11eb-892f-58dd833c248e.png)

## Environment

atoti: 0.5.1
Operating System: win32

**Comment by tibdex** [comment] 2021-01-18 15:04
> However, in the search list, I could only reach alphabet J.

Indeed, only the first 10,000 results are displayed in the tree. I agree that the UI lacks a feedback to tell you about this.

> I couldn't even use the search box to select the intended player

What do you mean you couldn't use the search box? Was it unresponsive or did it crash?

**Comment by HuifangYeo** [comment] 2021-01-19 07:06
Hi @tibdex,

Sorry I meant to say when I tried to use the search box, it didn't return me any results.

![image](https://user-images.githubusercontent.com/35210495/104999452-d4028b80-5a67-11eb-810c-aa9f79d8a9bb.png)

**Comment by tibdex** [comment] 2021-01-19 10:46
I was able to reproduce. It's because the search is done client side and so has only access to the first 10,000 members too.

**Comment by antoinetissier** [comment] 2021-01-26 10:50
This has changed in the latest version ActiveUI 5 SDK (thanks to this [PR in our internal repository](https://github.com/activeviam/activeui-5/pull/750)): we now perform the search on the server side by using `MembersCaptionSearch` in the MDX query responsible for fetching members.

**Comment by bloussou** [comment] 2021-08-06 15:14
I'm closing this since AUI has been updated in `0.6.0` the issue is resolved

**Closed by bloussou** 2021-08-06 15:14 UTC
Labels: bug :bug:, ui :bar_chart:, waiting dependency :hourglass_flowing_sand:
