### ISSUE TITLE
Error occurred when filtering by date - Empty list of fields to retrieve from the store

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#257] opened 2021-03-26 08:32 UTC
## Steps to reproduce

![vector-date-filter](https://user-images.githubusercontent.com/35210495/112603931-9697f100-8e50-11eb-8fe6-454eaa47815f.gif)

Please refer to https://github.com/atoti/notebooks/blob/master/notebooks/stressed-var-calibration/main.ipynb for the notebook, the visualization under "Creating Sliding Windows" section.

## Environment

- atoti: 0.5.2
- Operating System: win32
- Browser: Chrome

**Comment by tibdex** [comment] 2021-03-31 15:54
I was able to reproduce with this [minimal notebook](https://github.com/atoti/atoti/files/6237813/main.ipynb.zip).

**Comment by bloussou** [comment] 2022-01-27 15:07
Closing as I cannot reproduce with atoti `0.6.4`

**Closed by bloussou** 2022-01-27 15:07 UTC
Labels: :bug: bug
