### ISSUE TITLE
Unhelpful error message when trying to agg an existing measure and no scope is provided

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#633] opened 2022-07-06 13:48 UTC
## Description

When you try to create a new measure from the agg module and forget to pass a scope, the error message is this one:
```
AtotiJavaException: A measure aggregation cannot be performed without leaf levels
```
A developper has no idea of what is a leaf levels, a message indicating that you have to pass a scope (and maybe explaining why) would be more helpfull.

**Comment by CamilleBlanco** [comment] 2022-07-07 14:23
Hi Alexis, 

I add this ticket to our backlog. Thank you the advice 😃

**Comment by tibdex** [comment] 2022-07-13 16:37
Looks like a duplicate of #453.

**Closed by tibdex** 2022-07-13 16:37 UTC
