### ISSUE TITLE
Cannot load pandas DataFrame with a column where all values are null 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#547] opened 2022-03-31 10:29 UTC
## Steps to reproduce
In the notebook gallery, the Twitter notebook has a Pandas Dataframe that has 2 columns containing list objects. 
![image](https://user-images.githubusercontent.com/35210495/161033623-412ec8c5-f9b6-42c8-a212-406609503eb6.png)

In 0.6.4, I'm able to run `read_pandas` on the dataframe but in v0.6.5, I encountered the error:
<details><pre>
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3116\41890350.py in <module>
----> 1 stats_table = session.read_pandas(
      2     data_stats, keys=["coin_symbol", "metric_name"], table_name="statistics", types={}
      3 )
      4 stats_table.head()

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti\_runtime_type_checking_utils.py in typechecked_func_wrapper(*args, **kwargs)
    177 
    178             # Call the actual function.
--> 179             return self._func(*args, **kwargs)
    180 
    181         # Mark the function as typechecked and return it.

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti_core\doc.py in wrapper(*args, **kwargs)
     19         @wraps(function)
     20         def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> Any:
---> 21             return function(*args, **kwargs)
     22 
     23         # Collecting docstring and docstring templates

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti\session.py in read_pandas(self, dataframe, table_name, keys, partitioning, types, hierarchized_columns, **kwargs)
    352         """
    353         arrow_table = pandas_to_arrow(dataframe, types=types)
--> 354         return self._read_arrow(
    355             arrow_table,
    356             table_name=table_name,

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti\session.py in _read_arrow(self, arrow_table, table_name, keys, partitioning, types, hierarchized_columns, **kwargs)
    373         **kwargs: Any,
    374     ) -> Table:
--> 375         types_from_arrow = get_data_types_from_arrow(
    376             arrow_table,
    377             keys=keys,

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti\_arrow_utils.py in get_data_types_from_arrow(table, keys)
     56 ) -> Dict[str, DataType]:
     57     arrow_types = table.schema.types
---> 58     return {
     59         table.column_names[i]: DataType(
     60             java_type=_ARROW_TYPES[arrow_type].java_type,

~\AppData\Local\pypoetry\Cache\virtualenvs\notebooks-9JwRG8My-py3.9\lib\site-packages\atoti\_arrow_utils.py in <dictcomp>(.0)
     58     return {
     59         table.column_names[i]: DataType(
---> 60             java_type=_ARROW_TYPES[arrow_type].java_type,
     61             nullable=_ARROW_TYPES[arrow_type].nullable
     62             and (table.column_names[i] not in keys),

KeyError: DataType(null)
</pre></details>

Drug Efficacy notebook also has list in one of the table but has no such issue.
![image](https://user-images.githubusercontent.com/35210495/161034097-3bebb7ec-b030-41d4-a7e0-0dc2b0beaf4f.png)

The difference between the type:
Drug Efficacy:
![image](https://user-images.githubusercontent.com/35210495/161034530-e68f4966-5522-4f50-8168-7d481eb461fc.png)

Twitter:
![image](https://user-images.githubusercontent.com/35210495/161034661-7ba15975-a14a-48b5-b0ac-1ea4562d6f04.png)

[twitter.zip](https://github.com/atoti/atoti/files/8388444/twitter.zip)

## Environment

- atoti: 0.6.5
- Python: 3.9.12
- Operating system: win32

**Comment by bloussou** [comment] 2022-03-31 13:00
Hello,
The issue is coming from column with columns where all values are null. You define the `types` of these columns as a workaround while we are working for a fix.

**Comment by HuifangYeo** [comment] 2022-04-01 01:50
Thanks @bloussou! I overcomed with the below. However, I have a question, why must I set the types for the array as `tt.type.NULLABLE_FLOAT_ARRAY` (I received error message for `tt.type.FLOAT_ARRAY`)?

```
stats_table = session.create_table(
    name="statistic",
    types={
        "coin_symbol": tt.type.STRING,
        "metric_name": tt.type.STRING,
        "norm_stat": tt.type.FLOAT,
        "norm_p": tt.type.FLOAT,
        "kurtosis": tt.type.FLOAT,
        "skewness": tt.type.FLOAT,
        "lag_acf": tt.type.NULLABLE_FLOAT_ARRAY,
        "lag_pacf": tt.type.NULLABLE_FLOAT_ARRAY,
        "std": tt.type.FLOAT,
        "durbin_watson": tt.type.FLOAT,
    },
    keys=["coin_symbol", "metric_name"],
)

stats_table.load_pandas(data_stats)
```

**Comment by bloussou** [comment] 2022-04-01 07:39
I don't know,k it should be the type expected if values are not null to be able to load value after the table creation.

**Comment by bloussou** [comment] 2022-04-07 07:06
Hello,
This will be fixed in the next release

**Closed** 2022-05-20 15:07 UTC
Labels: :bug: bug
