### ISSUE TITLE
Create year, quarter, month, week and date from date time field on-the-fly

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#181] opened 2020-11-10 05:04 UTC
Could you please consider providing an easy way to generate a hierarchy for calendar aggregation.

As is:

it is possible to create a field in the input data, and then use it for aggregation - for example, week number. However, if at a later point you want to start aggregating by month - you need to reload all data, as it's not possible to add a column into the datastore.

To be:

Please consider adding a feature to generate calendar attributes from date columns using atoti.

Use cases:

Monthly performance, weekly sales, daily volume, etc.

**Comment by APolyakova** [comment] 2020-11-10 05:27
Please see the similar function in pandas: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.resample.html

**Comment by fabiencelier** [comment] 2020-11-10 09:35
I am closing this as a duplicate of #171 as I think it is the same feature request (with quarter and week number added).

Let me know if I'm wrong

**Closed by fabiencelier** 2020-11-10 09:35 UTC
Labels: duplicate :dancing_women:, enhancement :sparkles:
