### ISSUE TITLE
Improve pip installation doc

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#61] opened 2020-06-04 12:21 UTC
## Description

I had several questions/feedback from people trying to install the library with `pip`. It seems to be a quite popular option actually.

Suggestions:
1. list where to manually download the wheel: https://pypi.org/project/atoti/#files (maybe in a troubleshoot section?)
1. add a list of dependencies (and their wheels url?) for full manual install `pandas`, `pyarrow`, `pyyaml` and `typing_extensions`.
1. add url linking to how to install each of the prerequisite or even the command on how to install it like we do for JupyterLab: `Python`, `JDK`, `Node.js` and `JupyterLab`

**Comment by fabiencelier** [comment] 2020-06-04 16:51
> add url linking to how to install each of the prerequisite or even the command on how to install it like we do for JupyterLab: Python, JDK, Node.js and JupyterLab

We could link to these: https://adoptopenjdk.net/, https://nodejs.org/en/ and https://www.python.org/downloads/ 
There are other ways to install them but I agree that providing at least one solution is nice

> add a list of dependencies (and their wheels url?) for full manual install pandas, pyarrow, pyyaml and typing_extensions

I agree with tibdex that it is not our job to list and distribute our dependencies artifacts. If someone has no access to pypi but access to our wheel, pip should tell them what dependencies cannot be installed.

If no access to pypi is a common issue an alternative solution might be to have our own public channel caching the dependencies but that assumes the user can access our channel. And it is a lot of work to maintain and update so I'd rather wait to see if it is a common issue

> list where to manually download the wheel: https://pypi.org/project/atoti/#files (maybe in a troubleshoot section?)

we could have a troubleshot section as long as we answer atoti specific installation issues and not all generic issues with conda/pip/docker.
If we want it this it might deserve another issue to discuss what content we want and where to put it (one per install page or a single after all the install ?)

**Comment by rcolle** [comment] 2020-06-04 19:48
Agree with both. 
One thing we could do though is to add a sentence on each install page asking to contact us if they cannot access the remote repository:

**Comment by jbe456** [comment] 2020-06-05 07:48
>One thing we could do though is to add a sentence on each install page asking to contact us if they cannot access the remote repository

Good idea. But in that case I would not be problem specific. "Need help on installation? contact us on [Gitter](https://gitter.im/atoti/atoti), [Github](https://github.com/atoti/atoti/issues) or shoot us an [email](mailto:support@atoti.io)."

>Do we want to have in our docs, some non-atoti specific content [...]?

This is an old recurring debate. Nobody here asked to duplicate installation tutorial from other tools, just adding links to them.

Now all things considered, listing all dependencies is probably not going to help much. Seems pretty advanced and failure prone. However, having at least a link to https://pypi.org/project/atoti is reasonable. Something at the beginning of the doc that says "atoti is available on the official PyPI repository: https://pypi.org/project/atoti"

Reason I'm suggesting this: if you think about the last person who reached out to me for PyPI installation issue, he was looking to download the wheel manually. Had he thought about going to that link he would have tried what he had in mind and would have then reached out to the IT (which was his second option). Plus it can only help to have a "shortcut" to that page from the installation page.

**Comment by rcolle** [comment] 2020-06-05 07:50
The problem is, if his proxy is blocking pypi, he won't be able to download it from the web link either.

**Comment by jbe456** [comment] 2020-06-29 13:56
To summarize the points developed above:
- add a sentence "Need help on installation? contact us on [Gitter](https://gitter.im/atoti/atoti), [Github](https://github.com/atoti/atoti/issues) or shoot us an [email](mailto:support@atoti.io)."
- add a sentence "atoti is available on the official PyPI repository: https://pypi.org/project/atoti"

Another thing to improve the installation: after several user interviews I think we can safely assume that people jump straight to code snippet and only read the rest if necessary.

In particular, people don't read this (even with the red part)
![image](https://user-images.githubusercontent.com/4415696/86014179-48200800-ba20-11ea-8fec-1bd8d5452acf.png)

So we could change the doc to have people run a command to check if those requirements are met:
``` console
# prerequisites
echo "Prerequisites:"
echo "- JDK $(java -version 2>&1 | awk '/version/{print $3}') >= 11"
echo "- Node $(node -v) >= 10"
echo "- $(python --version) >= 3.7"
echo "Are the following requirements met?"
read
```

That alone would draw attention to that first step. We could also rename `Requirements` into `Install dependencies` as the keyword install should also drew more attention.

**Comment by jbe456** [comment] 2020-07-03 15:08
Another user interviewed did not install the requirements. He suggested that we do something similar than what https://github.com/psycopg/psycopg2 does on install.

They are able to throw when one of those required "dependencies" is not installed (in the example Microsoft Visual C++). 

See for example:
- https://stackoverflow.com/questions/58698359/getting-error-while-installing-psycopg2-in-vscode-on-windows
- https://stackoverflow.com/questions/28611808/how-to-install-psycopg2-for-python-3-5
- https://stackoverflow.com/questions/57581571/pip-install-error-microsoft-visual-c-10-0-is-required

What do you think of providing a similar mechanism on install for each of the "requirements"? something that would throw if they would not be installed or installed with the wrong version?

**Comment by fabiencelier** [comment] 2020-09-24 10:24
The requirements have been reduce as we no longer depend on Java manually installed.
There is no plan to check for the "non pip" dependencies during the Pip install at the moment so I'm closing this issue.

**Closed by fabiencelier** 2020-09-24 10:24 UTC
Labels: documentation :book:, installation :minidisc:
