### ISSUE TITLE
Unable to apply filter through search when list is long

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#347] opened 2021-08-26 06:40 UTC
## Steps to reproduce

I have 24,620 driver refs and when I try to search for a particular driver, the "Apply filter" is disabled.
Without filtering, I can see the drivers exist in the query. Once I manually select the drivers, the return table is empty:
![filter_selection](https://user-images.githubusercontent.com/35210495/130912824-783cf3ff-dd38-406f-a261-032ff1e80087.gif)

Please see last cell of attached notebook: [main.zip](https://github.com/atoti/atoti/files/7052141/main.zip)

## Environment
- atoti: 0.6.1
- Operating System: win32

**Comment by bloussou** [comment] 2022-01-27 10:34
I'm closing this since I cannot reproduce with AUI 5.0.7

**Closed by bloussou** 2022-01-27 10:34 UTC
Labels: :bug: bug, :lipstick: ui
