### ISSUE TITLE
Error when creating a join: The level cannot be found in the cube.

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#433] opened 2021-12-08 15:29 UTC
## Steps to reproduce

This is a bit complex to reproduce as you need 3 stores, one normal join and one partial join based on the same fields but with different names

```python
import pandas as pd, atoti as tt
session = tt.create_session()
s1 = session.read_pandas(
    pd.DataFrame({
        "ID": [1,2,3],
        "Product": ["a", "b","c"],
        "Amount": [10.0, 20.0, 30.0]}),
    table_name = "s1"
)

s2 = session.read_pandas(
    pd.DataFrame({
        "MyProduct": ["a", "b","c"],
        "Price": [100.0, 200.0, 300.0]}),
    table_name = "s2",
    keys=["MyProduct"]
)

s3 = session.read_pandas(
    pd.DataFrame({
        "YetAnotherProduct": ["a", "b","c", "a", "b", "c"],
        "AntoherKey": [1,1,1,2,2,2]}),
    table_name = "s3",
    keys = ["YetAnotherProduct", "AntoherKey"]
)

s1.join(s2, mapping={"Product": "MyProduct"})
cube = session.create_cube(s1)

s2.join(s3, mapping={"MyProduct": "YetAnotherProduct"})
```

<pre>
AtotiJavaException: An error occurred while calling o163.refresh.
: com.activeviam.copper.exception.UserErrorException: The level Level[level=MyProduct] cannot be found in the cube. If the level belongs to a non-Copper analysis hierarchy, try setting the IAnalysisHierarchy.LEVEL_TYPES_PROPERTY property.
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.findLevelInformation(CubeHelper.java:399)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.lambda$getLevelInformation$0(CubeHelper.java:313)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.computeIfAbsent(CubeHelper.java:339)
	at com.activeviam.copper.CubeHelper$LevelInformationRetriever.getLevelInformation(CubeHelper.java:313)
	at com.activeviam.copper.CubeHelper.getLevelInformation(CubeHelper.java:137)
	at com.activeviam.copper.CubeHelper.getLevelIdentifier(CubeHelper.java:112)
	at com.activeviam.copper.store.Mapping.createMappingForProcedure(Mapping.java:81)
	at com.activeviam.copper.store.JoinKey.from(JoinKey.java:52)
	at com.activeviam.copper.hierarchy.CopperJoinHierarchyBuilderWithField.publish(CopperJoinHierarchyBuilderWithField.java:72)
	at com.activeviam.copper.hierarchy.CopperJoinHierarchyBuilderWithField$CopperLevelFromFieldBuilder.publish(CopperJoinHierarchyBuilderWithField.java:90)
	at com.activeviam.copper.hierarchy.CopperJoinHierarchyBuilderWithField$CopperLevelFromFieldBuilder.publish(CopperJoinHierarchyBuilderWithField.java:79)
	at io.atoti.pivot.impl.SingleLevelCopperHierarchy.doPublish(SingleLevelCopperHierarchy.java:109)
	at io.atoti.pivot.measure.util.ACopperHierarchyDefinition.publish(ACopperHierarchyDefinition.java:18)
	at io.atoti.pivot.impl.HierarchiesManager.lambda$publishCopper$16(HierarchiesManager.java:543)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.atoti.pivot.impl.HierarchiesManager.publishCopper(HierarchiesManager.java:543)
	at io.atoti.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:27)
	at io.atoti.postprocesssor.impl.UserCopperMeasuresDescriptionPostProcessor.accept(UserCopperMeasuresDescriptionPostProcessor.java:11)
	at com.activeviam.copper.CopperDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CopperDescriptionPostProcessor.java:93)
	at io.atoti.pivot.impl.CubeImpl$CopperActivePivotDescriptionPostProcessor.enrichDescriptionWithCopperCalculations(CubeImpl.java:731)
	at com.activeviam.copper.CopperDescriptionPostProcessor.postProcessActivePivotDescription(CopperDescriptionPostProcessor.java:63)
	at com.quartetfs.biz.pivot.impl.ActivePivotSchemaBuilder.postProcess(ActivePivotSchemaBuilder.java:1029)
	at com.quartetfs.biz.pivot.impl.ActivePivotManagerBuilder.postProcess(ActivePivotManagerBuilder.java:267)
	at io.atoti.pivot.impl.CubeManager.toManagerDesc(CubeManager.java:118)
	at io.atoti.impl.SimpleManager.includePivotChangesToDatastore(SimpleManager.java:424)
	at io.atoti.impl.SimpleManager.refresh(SimpleManager.java:300)
	at io.atoti.api.impl.BaseApi.refresh(BaseApi.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
</pre>

## Environment

- atoti: 0.6.3
- Operating System: Linux

**Comment by bloussou** [comment] 2021-12-09 16:35
It is because you don't have a level `MyDate` in your cube. 
`h["MyProduct"] = [s2["MyProduct"]]` must be done before creating the second join.
I'm checking how it was done in `0.6.2` but I think it is the expected behavior

**Comment by Skyscimitar** [comment] 2021-12-09 16:40
This seems like an actual issue, since the `Product` and `MyProduct` keys are mapped together with a regular join, the level `lvl["Product"]` should be able to be used for the copper join with the third table.

**Comment by bloussou** [comment] 2021-12-09 16:46
ok then I will try to reproduce this in the core

**Comment by bloussou** [comment] 2021-12-23 10:16
Hello, it will be fixed in the next release !

**Comment by fabiencelier** [comment] 2021-12-29 10:46
Nice, thank you !

**Closed** 2022-01-16 21:01 UTC
Labels: :bug: bug
