### ISSUE TITLE
measure removed from visualization remains in mdx

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#283] opened 2021-05-27 08:44 UTC
## Steps to reproduce

Hi, I have performed sorting by a measure. I removed the measure after renaming it from `f_bump` to  `PLvalue_bump`.
However, `f_bump` remains in the MDX for the sorting clause.

![image](https://user-images.githubusercontent.com/35210495/119794774-6a5d2700-bf0a-11eb-8916-ebbd4846fb9a.png)

## Environment

- atoti: 0.5.5
- Operating System: win32

**Comment by tibdex** [comment] 2021-05-27 08:59
Hi Hui Fang could you please share a GIF so that we can better understand the flow of what you did?

**Comment by HuifangYeo** [comment] 2021-05-27 10:15
Hi @tibdex,

please see the GIF below:
![removed_filter_mdx](https://user-images.githubusercontent.com/35210495/119809250-7ef3ec00-bf17-11eb-847a-97690f540e9d.gif)

**Comment by tibdex** [comment] 2021-05-27 10:46
Thanks I was able to reproduce it 👍🏻.

**Comment by mtadams007** [comment] 2021-05-28 12:02
Tracking internally in this [ticket](https://support.activeviam.com/jira/browse/UI-5938)

**Comment by bloussou** [comment] 2022-01-27 14:22
Closing this as I cannot reproduce with the latest atoti version :
![Peek 2022-01-27 15-20](https://user-images.githubusercontent.com/32448554/151377508-7121dcf2-3c4d-4d4f-9a9e-aa2a6457c79c.gif)

**Closed by bloussou** 2022-01-27 14:22 UTC
Labels: :bug: bug, :lipstick: ui, :hourglass_flowing_sand: waiting dependency
