### ISSUE TITLE
Failed to parse parquet

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#306] opened 2021-06-22 12:39 UTC
## Steps to reproduce

Please see the attached notebook.
I was able to read AtotiUpload_2.parquet with atoti. However, I modified the parquet file with pyarrow.
I was able to read the new AtotiUpload_1.parquet with Pandas but not with atoti.

[parquet.zip](https://github.com/atoti/atoti/files/6694244/parquet.zip)

## Environment
- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

## Logs (if relevant)
<details><pre>
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<ipython-input-3-0cfe39ecbfba> in <module>
      1 parquet = session.read_parquet("AtotiUpload_1.parquet")
----> 2 parquet.head()

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\_type_utils.py in typechecked_func_wrapper(*args, **kwargs)
    194 
    195             # Call the actual function.
--> 196             return self._func(*args, **kwargs)
    197 
    198         # Mark the function as typechecked and return it.

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\_docs_utils.py in wrapper(*args, **kwargs)
     14         @wraps(func)
     15         def wrapper(*args: Any, **kwargs: Any) -> Callable:
---> 16             return func(*args, **kwargs)
     17 
     18         # Collecting docstring and docstring templates

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\store.py in head(self, n)
    220             raise ValueError("n must be at least 1.")
    221 
--> 222         return self._java_api.get_store_dataframe(self, n, self.scenario, self.keys)
    223 
    224     @doc(**{**STORE_SHARED_KWARGS, **CSV_KWARGS})

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     64     def catch_py4j_exceptions(java_api: JavaApi, *args: Any, **kwargs: Any) -> Any:
     65         try:
---> 66             return method(java_api, *args, **kwargs)
     67         except Py4JJavaError as java_exception:
     68             cause = (

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\_java_api.py in get_store_dataframe(self, store, rows, scenario_name, keys)
    661     ) -> pd.DataFrame:
    662         """Return the first given rows of the store as a pandas DataFrame."""
--> 663         self.start_feeding()
    664         dfrh = self.java_api.dataFrameRowsAndHeaders(store.name, scenario_name, rows)
    665 

C:\Apps\miniconda3\envs\atoti\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     71                 else f"{java_api.get_throwable_root_cause(java_exception.java_exception)}"
     72             )
---> 73             raise AtotiJavaException(
     74                 cause,
     75                 str(java_exception),

AtotiJavaException: Failed to parse C:/Users/Yeo Hui Fang/Documents/GitHub/notebooks2/support/piyumal_parquet/AtotiUpload_1.parquet
</pre></details>

**Comment by bloussou** [comment] 2021-06-23 08:49
Which is your pyarrow version ?

**Comment by HuifangYeo** [comment] 2021-06-23 09:01
3.0.0

**Comment by fabiencelier** [comment] 2021-06-23 09:14
Adding the full Java stack trace:

<details>
<summary>Stack trace</summary>
<pre>
AtotiJavaException: An error occurred while calling t.refresh.
: com.activeviam.fwk.ActiveViamRuntimeException: Failed to parse /home/jovyan/work/AtotiUpload_1.parquet
	at com.activeviam.parquet.impl.ParquetParser.waitForParsingCompletion(ParquetParser.java:672)
	at com.activeviam.parquet.impl.ParquetParser.parse(ParquetParser.java:525)
	at io.atoti.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:79)
	at io.atoti.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:32)
	at io.atoti.util.files.LocalPath.accept(LocalPath.java:186)
	at io.atoti.loading.parquet.impl.ParquetDataTable.loadPathWithinTransaction(ParquetDataTable.java:123)
	at io.atoti.loading.impl.AFileBasedDataTable.loadWithinTransaction(AFileBasedDataTable.java:88)
	at io.atoti.loading.impl.DataTableOperationUnit.executeOperation(DataTableOperationUnit.java:45)
	at io.atoti.loading.impl.DatastoreOperation.lambda$load$0(DatastoreOperation.java:63)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2745)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.performInTransaction(FlexibleTransactionManager.java:193)
	at io.atoti.loading.impl.DatastoreOperation.load(DatastoreOperation.java:60)
	at io.atoti.loading.impl.DatastoreOperation.load(DatastoreOperation.java:32)
	at io.atoti.impl.SimpleAtotiManager.loadOperation(SimpleAtotiManager.java:570)
	at io.atoti.impl.SimpleAtotiManager.lambda$feed$5(SimpleAtotiManager.java:636)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at io.atoti.impl.SimpleAtotiManager.feed(SimpleAtotiManager.java:636)
	at io.atoti.impl.SimpleAtotiManager.startFeeding(SimpleAtotiManager.java:585)
	at io.atoti.impl.SimpleAtotiManager.resume(SimpleAtotiManager.java:399)
	at io.atoti.impl.SimpleAtotiManager.refresh(SimpleAtotiManager.java:445)
	at io.atoti.AtotiSession.refresh(AtotiSession.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.activeviam.parquet.impl.ParquetParser.waitForParsingCompletion(ParquetParser.java:670)
	... 32 more
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at io.atoti.loading.parquet.visitor.ParquetDiscoveryPathVisitor.lambda$matchParquetType$1(ParquetDiscoveryPathVisitor.java:117)
	at com.activeviam.parquet.impl.StoreToParquetMappingBuilder.lambda$map$0(StoreToParquetMappingBuilder.java:163)
	at com.activeviam.parquet.impl.ParquetParser.writeRecord(ParquetParser.java:831)
	at com.activeviam.parquet.impl.ParquetParser.writeRecordToBlocks(ParquetParser.java:718)
	at com.activeviam.parquet.impl.ParquetParser.parseInOneThread(ParquetParser.java:316)
	at com.activeviam.parquet.impl.ParquetParser.parseInOneThread(ParquetParser.java:188)
	at com.activeviam.parquet.impl.ParquetParser.lambda$parse$4(ParquetParser.java:516)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
</pre>
</details>

**Comment by bloussou** [comment] 2021-07-06 13:40
It will be fixed in the next version

**Closed** 2021-07-20 12:21 UTC
Labels: bug :bug:
