### ISSUE TITLE
Cannot delete None/Null values from table

### ISSUE THREAD

**Issue by shahin-y** [atoti/atoti#610] opened 2022-06-14 10:53 UTC
Hi there,

calling `table.drop({"column_name": None})` does not delete columns containing `None` values but the entire content of the table - see example below.

Furthermore, the [documentation](https://docs.atoti.io/latest/lib/atoti/atoti.table.html#atoti.Table.drop) suggests that all rows are only deleted if the `coordinates` are `None`. However, as there is no distinction between `None` and 'falsy' `coordinates` in `_java_api.py::delete_rows_from_table` providing an empty mapping (i.e. `table.drop({})`) has the same effect. When deriving the `coordinates` dynamically that becomes an important detail 😉

## Steps to reproduce

```python
import atoti as tt
import pandas as pd

data = df = pd.DataFrame(
    columns=["City", "Price"],
    data=[
        ("London", 240.0),
        ("New York", 270.0),
        ("Paris", 200.0),
        ("Nantes", None),
        ("Frankfurt", None)
    ],
)

session = tt.Session()
table = session.read_pandas(data, table_name="data")

session.create_cube(table)
print(f"Price column is nullable: {table['Price'].data_type.nullable}")
table.head(20)
```
<html>
<body>

 City | Price
 -- | --
London | 240.0
New York | 270.0
Paris | 200.0
Nantes | NaN
Frankfurt | NaN

</body>
</html>

Let's try do delete entries with None/Null values:
```python
table.drop({"Price": None}) # drops the table's entire data
```
## Actual Result

<html>
<body>

  | City | Price
-- | -- | --

</body>
</html>

## Expected Result
 City | Price
 -- | --
London | 240.0
New York | 270.0
Paris | 200.0

</body>
</html>

## Environment

- atoti: 0.6.6
- Python: 3.8.10
- Operating System: Windows 10

**Comment by CamilleBlanco** [comment] 2022-06-15 16:04
Hi!

Indeed I can reproduce with the following code:
```python 
    import atoti as tt
    import pandas as pd


    data = pd.DataFrame(
        columns=["City", "Price"],
        data=[
            ("London", 240.0),
            ("New York", 270.0),
            ("Paris", 200.0),
            ("Nantes", None),
            ("Frankfurt", None),
        ],
    )

    session = tt.Session()
    table = session.read_pandas(data, table_name="data")

    table.drop({"Price": None})
```
We will work on it and let you know how when it is fixed. Many thanks for reporting it!

**Comment by bloussou** [comment] 2022-07-11 13:18
AP PR : https://github.com/activeviam/activepivot/pull/5242

**Comment by tibdex** [comment] 2022-07-11 13:49
Since this is waiting on an upstream development, for now we should raise a clear error on the Python side when one of the coordinates contains a `None` value.

**Comment by mailys-ds** [comment] 2022-07-11 16:19
Task list: 
- [ ] [Raise `NotImplementedError` when dropping null values](https://github.com/activeviam/atoti/pull/3710)
- [ ] Integrate [AP development ](https://github.com/activeviam/activepivot/pull/5242) that fixes the issue

**Comment by bloussou** [comment] 2022-07-26 16:01
Hello,
This will be fixed in the next release

**Closed** 2022-08-16 22:41 UTC
Labels: :bug: bug
