### ISSUE TITLE
NPE when doing references

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#434] opened 2021-12-08 16:44 UTC
## Steps to reproduce
Hello, 
I have a notebook with 2 references, one of them is throwing this error. It is on a PoC scope, the notebook is running on a private EC2 instance to ActiveViam, I can share it with you on demand via Slack.
![Exception](https://user-images.githubusercontent.com/7359377/145248008-fc2269d9-b0e5-4865-9d6a-58746dc0a712.PNG)

## Environment
- atoti: 0.6.3
- Python: 3.10.0
- Operating System: linux

## Logs
Full logs: [full_logs.txt](https://github.com/atoti/atoti/files/7677551/full_logs.txt)
```
java.lang.NullPointerException: null
	at com.activeviam.store.structure.impl.InPlaceSchemaUpdates$2$1.onChunkCompletion(InPlaceSchemaUpdates.java:596) ~[datastore-5.11.0-20211115.jar!/:na]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.IntPipeline$Head.forEachOrdered(Unknown Source) ~[na:na]
	at com.qfs.store.impl.ColumnarRecordSet.scan(ColumnarRecordSet.java:868) ~[datastore-5.11.0-20211115.jar!/:na]
	at com.activeviam.store.structure.impl.InPlaceSchemaUpdates$2.lambda$computeSafely$2(InPlaceSchemaUpdates.java:609) ~[datastore-5.11.0-20211115.jar!/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.IdentityHashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at com.activeviam.store.structure.impl.InPlaceSchemaUpdates$2.computeSafely(InPlaceSchemaUpdates.java:554) ~[datastore-5.11.0-20211115.jar!/:na]
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.execSafely(CancellableCountedCompleter.java:163) ~[atoti-aws.jar:na]
	at com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:190) ~[atoti-aws.jar:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
```

**Comment by bloussou** [comment] 2021-12-08 17:12
duplicate of https://github.com/activeviam/atoti/issues/2965

**Closed by bloussou** 2021-12-08 17:12 UTC
Labels: :bug: bug
