### ISSUE TITLE
TypeError: missing a required argument: 'name' when creating the session

### ISSUE THREAD

**Issue by nithinreddyy** [atoti/atoti#550] opened 2022-04-04 06:36 UTC
When i'm trying to create a session, it's returning an error like TypeError: missing a required argument: 'name'. Below is the code

`session = tt.Session()`

The error is 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_36564\3204545261.py in <module>
----> 1 session = tt.Session()

~\miniconda3\lib\site-packages\atoti\_runtime_type_checking_utils.py in typechecked_func_wrapper(*args, **kwargs)
    179         def typechecked_func_wrapper(*args: Any, **kwargs: Any) -> Any:
    180             # Perform typechecking on the input arguments.
--> 181             memo = typeguard._CallMemo(func=self._ts_func, args=args, kwargs=kwargs)
    182             typeguard.check_argument_types(memo)
    183 

~\miniconda3\lib\site-packages\typeguard\__init__.py in __init__(self, func, frame_locals, args, kwargs, forward_refs_policy)
    179 
    180         if args is not None and kwargs is not None:
--> 181             self.arguments = signature.bind(*args, **kwargs).arguments
    182         else:
    183             assert frame_locals is not None, 'frame must be specified if args or kwargs is None'

~\miniconda3\lib\inspect.py in bind(*args, **kwargs)
   3013         if the passed arguments can not be bound.
   3014         """
-> 3015         return args[0]._bind(args[1:], kwargs)
   3016 
   3017     def bind_partial(*args, **kwargs):

~\miniconda3\lib\inspect.py in _bind(self, args, kwargs, partial)
   2928                             msg = 'missing a required argument: {arg!r}'
   2929                             msg = msg.format(arg=param.name)
-> 2930                             raise TypeError(msg) from None
   2931             else:
   2932                 # We have a positional argument to process

TypeError: missing a required argument: 'name'
```

Can anyone help me how to resolve this issue?

**Comment by bloussou** [comment] 2022-04-04 07:16
Hello,
Which version of atoti are you using ? In `0.6.5` your code is working. In `0.6.4` it is not because you must use `tt.create_session()`.

**Comment by bloussou** [comment] 2022-05-11 12:48
I'm closing this since there is no answer and reproducible example.

**Closed by bloussou** 2022-05-11 12:48 UTC
Labels: :bug: bug
