### ISSUE TITLE
Incorrect TopCount returned result

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#98] opened 2020-07-06 06:18 UTC
## Steps to reproduce
Hi,

Referring to the attached notebook [customer-churn.zip](https://github.com/atoti/atoti/files/4877066/customer-churn.zip).
I have more than 1000 records:
![image](https://user-images.githubusercontent.com/35210495/86561387-157f8d80-bf93-11ea-8d7a-6eb7dc2329c4.png)
 I want the top 10 customers with the highest monthlyCharges:
![image](https://user-images.githubusercontent.com/35210495/86561442-3ba52d80-bf93-11ea-82d8-5dbcd1fa7eb0.png)

But only 8 records got returned.
![image](https://user-images.githubusercontent.com/35210495/86561503-5e374680-bf93-11ea-9a9f-eba13f16ad3e.png)

## Environment
- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by fabiencelier** [comment] 2020-07-06 09:25
I cannot run your examples as it uses dependency such as utils which is missing : `from utils import data_utils, prediction`

Can you please provide all the required  files or a more minimal example ?

This behavior can be caused by another filter removing some of the top 10 CustomerID, can you check if there is another filter ?

**Comment by HuifangYeo** [comment] 2020-07-06 09:27
Sorry, the attached utils:
[utils.zip](https://github.com/atoti/atoti/files/4877963/utils.zip)

**Comment by HuifangYeo** [comment] 2020-07-06 09:29
By removing all other filters, it returns me 6 records instead of the 10.
![image](https://user-images.githubusercontent.com/35210495/86578306-31445d00-bfae-11ea-9128-395038954522.png)

**Comment by fabiencelier** [comment] 2020-07-06 15:36
Looks like an issue in ActivPivot. I don't always have the issue but I can reproduce it with this small example:

```python
import atoti as tt
import pandas as pd
df = pd.DataFrame({
    "CustomerID": ['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU', '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU', '9763-GRSKD', '7469-LKBCI', '8091-TTVAX', '0280-XJGEX', '5129-JLPIS', '3655-SNQYZ'],
    "MonthlyCharges": [ 29.85,  56.95,  53.85,  42.3,  70.7,  99.65,  89.1,  29.75, 104.8,  56.15,  49.95,  18.95, 100.35, 103.7, 105.5, 113.25]
})
session = tt.create_session()
customer_store = session.read_pandas(
    df, keys=["CustomerID"], store_name="customer_store", partitioning="hash6(CustomerID)"
)
cube = session.create_cube(customer_store, "customer_cube")
cube.visualize()
```

Then make a pivot table with the following MDX query:

```
SELECT
  NON EMPTY {
    [Measures].[MonthlyCharges.SUM],
    [Measures].[contributors.COUNT]
  } ON COLUMNS,
  NON EMPTY Hierarchize(
    DrilldownLevel(
      [Hierarchies].[CustomerID].[ALL].[AllMember]
    )
  ) ON ROWS
  FROM (
    SELECT
    TopCount(
      Filter(
        [Hierarchies].[CustomerID].Levels(
          1
        ).Members,
        NOT IsEmpty(
          [Measures].[MonthlyCharges.SUM]
        )
      ),
      10,
      [Measures].[MonthlyCharges.SUM]
    ) ON COLUMNS
    FROM [customer_cube]
  )
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
```

This is all available in this notebook: 
[topcount.zip](https://github.com/atoti/atoti/files/4879911/topcount.zip)

I will open an internal issue.

**Comment by HuifangYeo** [comment] 2020-07-07 00:42
I think https://github.com/atoti/atoti/issues/99 is probably related as well.

**Comment by bloussou** [comment] 2020-08-17 14:07
Thanks for reporting, this will be fixed in next release.
Best

**Closed** 2020-09-01 11:52 UTC
Labels: bug :bug:
