### ISSUE TITLE
Dates coming from read_sql are not cast to the right types

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#263] opened 2021-03-31 10:02 UTC
## Steps to reproduce
Hi,

My data is loaded using `atoti.read_sql`:
```
consumption = session.read_sql(
    "jdbc:sqlserver://localhost:1433;databaseName=atoti",
    "SELECT CAST([Datetime] AS date) as ReportDate, * FROM [atoti].[atoti].[consumption];",
    username="atoti",
    password="atoti1",
    store_name="consumption",
    keys=["ZoneCode", "Year", "Month", "Day", "Hour", "WeekOfYear"],
#     types={"ReportDate": tt.type.LOCAL_DATE}
)
```
 I need to use date_diff to get the value of the previous day. 
`m["Previous"] = tt.date_shift(m["Consumption.SUM"], on=h["ReportDate"], offset="1D")`

I encountered the below exception:
![image](https://user-images.githubusercontent.com/35210495/113127261-2243c000-924b-11eb-8ce6-2f3a799957af.png)

## Environment
- atoti: 0.5.2
- Python: 3.9.1
- Operating System: win32

## Logs (if relevant)

<details><pre>
Caused by: java.lang.ClassCastException: class java.sql.Date cannot be cast to class java.time.LocalDate (java.sql.Date is in module java.sql of loader 'platform'; java.time.LocalDate is in module java.base of loader 'bootstrap')
	at com.activeviam.copper.hierarchy.CopperLevelIdentifier.lambda$at$3e3dfbfa$1(CopperLevelIdentifier.java:156) ~[activepivot-copper2-impl-5.10.0-20210209.jar!/:na]
	at com.activeviam.copper.pivot.pp.ShiftPostProcessor$ShiftEvaluationProcedure.shiftLocation(ShiftPostProcessor.java:723) ~[activepivot-copper2-impl-5.10.0-20210209.jar!/:na]
	at com.quartetfs.biz.pivot.postprocessing.impl.ALocationShiftPostProcessor$EvaluationProcedure.execute(ALocationShiftPostProcessor.java:309) ~[activepivot-ext-5.10.0-20210209.jar!/:na]
	at com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.forEachPoint(PointListRetrievalResult.java:936) ~[activepivot-impl-5.10.0-20210209.jar!/:na]
	at com.quartetfs.biz.pivot.postprocessing.impl.ALocationShiftPostProcessor.compute(ALocationShiftPostProcessor.java:146) ~[activepivot-ext-5.10.0-20210209.jar!/:na]
	at com.quartetfs.biz.pivot.query.aggregates.plan.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:174) ~[activepivot-impl-5.10.0-20210209.jar!/:na]
</pre></details>

**Comment by SBrown52** [comment] 2021-03-31 13:13
Common issus seen in CS, we usually use a column calculator to manually cast to a LocalDate

**Comment by rcolle** [comment] 2021-03-31 14:35
I assume that the issue is there:
https://github.com/activeviam/atoti/blob/f193a6a28fdd3e36772690254532abede56b34a8/java/patachou/core/src/main/java/io/atoti/pivot/measure/impl/AtotiDateShiftMeasure.java#L69

It'd indeed be better to have `LocalDate`/`LocalDateTime` instead of plain old `Date` Object though.

**Comment by SBrown52** [comment] 2021-03-31 14:43
From what I remember, there is something strange whereby you load a Date field from a database and although you specifically set the type in your datastore to be of `LocalDate`, what is actually stored is a `java.sql.Date` - perhaps that's what is in the dictionary. I never got to the bottom of this issue.

This makes any code like you posted @rcolle fail because you are trying to cast it. There are several APS tickets around this, perhaps if we have an environment whereby it can be reliable introduced then it can be investigated more.

**Comment by LisaWolffhugel** [comment] 2021-04-08 14:31
Hi guys, I have a similar issue. 
My store is created like this : 
```store_compteurs = session.read_sql(
    "jdbc:sqlserver://LISA-PC;databaseName=MonitoringDB",
    "SELECT [tagName] AS ID_compteur, YEAR(ts) AS Annee, DATENAME(month,ts) AS Mois, DAY(ts) AS Jour, FORMAT(ts, 'yyyy-MM-dd') as Date, [tagValue] AS valeur_compteur FROM [MonitoringDB].[dbo].[compteurs];",
    username="lisaW",
    password="qDa2021",
    store_name="compteurs",
    keys=["ID_compteur", "Date"],
    types={"ID_compteur":tt.type.STRING, "valeur_compteur": tt.type.DOUBLE},
)```

when I create my measure with date_shift using the method="exact" the creation is successful but there is the classcastexecption when visualizing it like Huifang explained. 

Besides, when using other methods like "previous "or "interpolate" I get this error when trying to visualize the measure:
 
![image](https://user-images.githubusercontent.com/82163268/114044647-afa89500-9887-11eb-8192-0e7d09fa59c6.png)

Any idea how we could get these measures to work ? 
Is there a way to cast Date to localdate directly in theSQL query ?

Thanks

**Comment by tibdex** [comment] 2021-04-09 09:49
We'll try to take a look at that before the upcoming release.

**Comment by LisaWolffhugel** [comment] 2021-04-15 13:07
Any update on this issue. Even when I load my store from a csv I have an issue when the method of the date_shift is other than **previous** but the behavior I'm looking for is the "**exact**" one.

**Comment by bloussou** [comment] 2021-04-15 13:56
Hi, I have a look at it, can you share a small example with a sample csv or a pandas dataframe ? It will help a lot to reproduce your issue.

**Comment by bloussou** [comment] 2021-04-15 14:08
`ClassCastException` will be fixed in the next release

**Comment by LisaWolffhugel** [comment] 2021-04-15 14:12
if it can be fixed for csv parsing and sql parsing that would be great 💯

**Comment by bloussou** [comment] 2021-04-15 14:20
@LisaWolffhugel what is the exact exception with csv ?

**Comment by LisaWolffhugel** [comment] 2021-04-15 14:28
@bloussou Same exception as @HuifangYeo mentioned in her 1st comment. If I load a csv and use "previous" everything works well if I use "exact" I  have the exception Huifang is mentioning about .

**Comment by bloussou** [comment] 2021-04-15 14:48
@LisaWolffhugel it is not possible to have `java.sql.Date` with csv file. Can you share your exact issue in order to fix it ?

**Closed** 2021-04-16 09:46 UTC
Labels: bug :bug:

**Comment by LisaWolffhugel** [comment] 2021-04-16 12:55
hi @bloussou here is the exception that I have: 
![image](https://user-images.githubusercontent.com/82163268/115027002-71ccf180-9ec3-11eb-9c9e-7ae98a6b7d56.png) it is a java.time.LocalDate exception. I'm reading a csv file and I used this : 
```
store_compteurs = session.read_csv("./data/V3/compteurs.csv",
                                       store_name="compteurs",
                                       keys=["ID_compteur", "Date"],
                                       types={"ID_compteur":tt.type.STRING, "Date": tt.type.LOCAL_DATE_TIME, "valeur_compteur": tt.type.DOUBLE})
```
![image](https://user-images.githubusercontent.com/82163268/115027188-afca1580-9ec3-11eb-8639-b30f5b2e4f49.png)

```
cube_measures["Valeur_precedente_compteur"] = tt.where(
    cube_levels["Type_intervalle"] == "Jour", 
           tt.date_shift(
                cube_measures["Valeur_compteur"],
                on=cube_hierarchies["Date"],
                offset="-1D",
                method="exact"
           )  ,
            tt.date_shift(
                cube_measures["Valeur_compteur"],
                on=cube_hierarchies["Date"],
                offset="-1W",
                method="exact"
            )
)
```
you can find the data here : https://github.com/LisaWolffhugel/emgt-nrj-monitoring/blob/master/data/V3/compteurs.csv
 hope this will help

**Comment by bloussou** [comment] 2021-04-16 13:28
Thanks for the example, do you reproduce with `0.5.3` which has just been released this morning ?

**Comment by LisaWolffhugel** [comment] 2021-04-16 13:31
I will try and let you know

**Comment by LisaWolffhugel** [comment] 2021-04-19 10:21
Hi guys, it seems everything works well on sql and csv with the version 0.5.3 . Thanks
