### ISSUE TITLE
Scope siblings with a level as an input

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#39] opened 2020-05-13 19:24 UTC
## Steps to reproduce

Take any measure using the scope siblings and pass it a level instead of a hierarchy:
```python
m["Champion Points"] = tt.agg.max(
    m["points.SUM"], scope=tt.scope.siblings(lvl["driverRef"])
)
```

For more context see https://github.com/atoti/atoti/issues/38

## Actual Result

It works as if it was a hierarchy, giving unexpected result if one think it accepts a level.

## Expected Result

Since it worked without any error, I was expecting siblings to operate on the `driverRef` level only while in fact it was also operating on the `ALL` level of the `driverRef` hierarchy.

I would expect to:
1. Either throw a meaningful error message asking to use a hierarchy instead. 
1. Or explicitly supports levels and make it operate on the siblings of that level only. See https://github.com/atoti/atoti/issues/38

## Environment

- Atoti: 0.4.0.20200512194154
- Python: 3.8.2
- Operating System: linux

**Comment by SamTaz** [comment] 2020-05-14 12:18
Even though in my case a hierarchy was passed to the scope siblings, could it be related to #16 ?

**Comment by fabiencelier** [comment] 2020-05-14 14:28
**About the bug:**
The scope.siblings only take a Hierarchy as argument. It is documented in the API signature but Python does not enforce types so you can pass anything. It works for your level by pure luck because we only take the name of the hierarchy with `hierarchy.name` and it happens that a level also have a name attributes.

I guess in your usecase the level and the hierarchy have the same name so when the level is provided is works as if the hierarchy is provided.

We do have plans to [add a more strict type checking on the public API](https://github.com/activeviam/atoti/issues/1382) to avoid such issues but it won't be ready soon.

**About scope.siblings:**
`scope.siblings` will work with a hierarchy, this is by design to apply on all level without hardcoding one.

**Comment by rcolle** [comment] 2020-06-12 15:25
This particular issue should be fixed by https://github.com/activeviam/atoti/pull/1404

**Closed** 2020-06-17 09:48 UTC
Labels: bug :bug:
