### ISSUE TITLE
Column width adjustment or tooltip for pivot table 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#251] opened 2021-03-04 05:11 UTC
## Steps to reproduce
For cells with values that are very long, there's no wraparound. Neither are we able to expand the width of the column or mouse over to see the tooltip:

![image](https://user-images.githubusercontent.com/35210495/109914483-0c45ec80-7ceb-11eb-98ef-c74cb283191f.png)

## Environment

- atoti: 0.5.2.20210302170500
- Operating System: win32

**Comment by tibdex** [comment] 2021-03-04 08:12
Hi Hui Fang, this is a duplicate of #206.

**Closed by tibdex** 2021-03-04 08:12 UTC
Labels: bug :bug:, ui :bar_chart:
