### ISSUE TITLE
An error occurred while calling t.refresh: Branch already exists

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#53] opened 2020-05-25 10:57 UTC
## Steps to reproduce
I have 2 measures simulation and 2 source simulations.
```
haircut_simulation = asset_positions_cube.setup_simulation(
    "Haircut Simulation",
    levels=[lvl["Sector"], lvl["Country"]],
    replace=[m["Haircut.VALUE"]],
    base_scenario="Current Market Condition",
)

market_value_simulation = asset_positions_cube.setup_simulation(
    "Market Value Simulation",
    levels=[lvl["Sector"], lvl["Country"]],
    multiply=[m["Price.VALUE"]],
    base_scenario="Current Market Condition",
)

# In Source Simulation, we do not perform simulation_setup. We just load it to the store as scenarios.
cashout_simulation = loans_positions_store.scenarios[
    "Cash out Increase"
].load_pandas(loans_positions_df, truncate=True)

predictive_simulation = assets_prices.scenarios["3 months forecast"].load_pandas(
    predictive_3_months, truncate=True
)
```

Error was thrown when I tried to create another measure simulation:
```
predictive_market_simulation = asset_positions_cube.setup_simulation(
    "x Simulation",
    levels=[lvl["Year_Month"], lvl["Sector"], lvl["Country"]],
    multiply=[m["Price.VALUE"]],
    replace=[m["Haircut.VALUE"]]
)
```

Run the attached notebook. Error is thrown from the last cell.

[collateral-shortfall-monitoring.zip](https://github.com/atoti/atoti/files/4676851/collateral-shortfall-monitoring.zip)

## Actual Result
```
Traceback (most recent call last):
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\exceptions.py", line 219, in catch_py4j_exceptions
    return method(*args, **kwargs)
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\_java_api.py", line 142, in refresh
    self.java_session.refresh(force_start)
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\vendor\atotipy4j\java_gateway.py", line 1313, in __call__
    return_value = get_return_value(
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\vendor\atotipy4j\protocol.py", line 322, in get_return_value
    raise Py4JJavaError(
Py4JJavaError: An error occurred while calling t.refresh.
: com.qfs.fwk.services.BadArgumentException: [400] the branch Cash out Increase already exists.
	at com.qfs.store.service.impl.DatastoreService.createBranch(DatastoreService.java:671)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.lambda$createBranch$1(RegisteringChouketDatastoreService.java:88)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService$DatastoreServiceOperation.initialLoad(RegisteringChouketDatastoreService.java:141)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.lambda$feed$3(SimpleActiveViamSession.java:629)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.feed(SimpleActiveViamSession.java:629)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.startFeeding(SimpleActiveViamSession.java:588)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:385)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-66-4b95227dae0f>", line 1, in <module>
    predictive_market_simulation = asset_positions_cube.setup_simulation(
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\cube.py", line 218, in setup_simulation
    simulation = Simulation(
  File "<string>", line 11, in __init__
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\simulation.py", line 114, in __post_init__
    self._java_api.refresh()
  File "C:\Apps\miniconda3\envs\atoti-0_4\lib\site-packages\atoti\exceptions.py", line 221, in catch_py4j_exceptions
    raise AtotiJavaException(
AtotiJavaException: An error occurred in the JVM:
An error occurred while calling t.refresh.
: com.qfs.fwk.services.BadArgumentException: [400] the branch Cash out Increase already exists.
	at com.qfs.store.service.impl.DatastoreService.createBranch(DatastoreService.java:671)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService.lambda$createBranch$1(RegisteringChouketDatastoreService.java:88)
	at com.activeviam.chouket.edit.impl.RegisteringChouketDatastoreService$DatastoreServiceOperation.initialLoad(RegisteringChouketDatastoreService.java:141)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.loadAndWatchOperation(SimpleActiveViamSession.java:568)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.lambda$feed$3(SimpleActiveViamSession.java:629)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.feed(SimpleActiveViamSession.java:629)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.startFeeding(SimpleActiveViamSession.java:588)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.resume(SimpleActiveViamSession.java:385)
	at com.activeviam.chouket.impl.SimpleActiveViamSession.refresh(SimpleActiveViamSession.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Environment
- Atoti: 0.4.0.20200511082531
- Python: 3.8.2
- Operating System: Windows 10 Pro

## Logs (if relevant)
[session_0.log](https://github.com/atoti/atoti/files/4676834/session_0.log)

**Comment by fabiencelier** [comment] 2020-05-28 14:03
This can be reproduced by refreshing the session after loading into a branch with truncate:

```python
import pandas as pd
import atoti

df = pd.DataFrame({
    "ProductId": [0, 1, 2, 3],
    "Price": [10.0, 8.0, 5.0, 12.0],
})
session = atoti.create_session()
store = session.read_pandas(df, store_name="store", keys=["ProductId"])
cube = session.create_cube(store)
store.scenarios["test"].load_pandas(df, truncate=True)
session._refresh()
```
This happens during `setup_simulation` because it is the next refresh

**Comment by fabiencelier** [comment] 2020-05-28 15:23
This will be fixed in the next release

**Closed** 2020-06-17 09:48 UTC
Labels: bug :bug:
