### ISSUE TITLE
Join, create_cube or setup_simulation retrigger the loading of data

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#32] opened 2020-05-07 20:17 UTC
## Description

When accessing the data is slow because of network issues and/or because the file is large, reading/loading the file takes time which is expected.

However, what's not expected, is that the following operations then become slow as well:

- joining stores
- creating the cube
- setting up a simulation

This problem has been highlighted in https://github.com/atoti/atoti/issues/26

Is there any plan to improve this?

## Context

- Atoti version: 0.3.1
- Python version: 3.8.2
- Operating System: linux

**Comment by fabiencelier** [comment] 2020-05-11 10:02
Hello,
This is due to an internal limitation that forces the datastore to restart entirely when the structure changes.

To understand more precisely what happens, there are 2 kinds of actions interacting with the datastore:
 - Some actions change the structure of the datastore: creating a store, adding a join, setting up a simulation...
 - Some actions require the datastore to be built: creating a cube, getting the first rows or the size of a store...

As the datastore needs to be restarted when the structure changes we try to build it as late as possible to avoid useless reloading: the first loading happens at the first action that requires it to be built. That's why you sometime see a `create_cube` command doing all the loading. After this first loading, any action that changes the structure will trigger a reload.

These are internal limitations, we have plans to improve this behavior in the future to avoid this inconvenience.
In the meantime, to avoid multiple long reloading we advise you to use a [sampling mode](https://docs.atoti.io/0.3.1/lib/atoti.html#module-atoti.sampling) until you project is fully defined.

**Comment by rcolle** [comment] 2020-06-11 14:11
Can you please provide a reproducible example for us to look at?
Thanks

**Comment by HuifangYeo** [comment] 2020-06-12 05:46
Hi,
with session.read_csv on a large data set on S3:
![image](https://user-images.githubusercontent.com/35210495/84467134-c3a65900-acad-11ea-9087-0df108bac925.png)

With Pandas on the same dataset:
![image](https://user-images.githubusercontent.com/35210495/84467186-edf81680-acad-11ea-994a-0e7657858d9a.png)
![image](https://user-images.githubusercontent.com/35210495/84467210-ffd9b980-acad-11ea-9fd1-161f7105aae0.png)

Creating a cube with multiple joins on stores reading from pandas:
![image](https://user-images.githubusercontent.com/35210495/84469111-e5eea580-acb2-11ea-8ad0-e226fc6c23e0.png)

For the one with atoti reading s3 directly, the cube is still running after 15minutes.

Please use the attached notebooks to simulate.
[geopricing.zip](https://github.com/atoti/atoti/files/4768955/geopricing.zip)

**Comment by rcolle** [comment] 2020-06-12 06:18
Thanks! Which version are you using?

**Comment by HuifangYeo** [comment] 2020-06-12 07:34
atoti 0.4.0

**Comment by rcolle** [comment] 2020-07-02 15:36
Here are some thoughts on the topic.

ActivePivot's s3 source is really efficient when the computer running atoti can saturate its 10Gbps network interface. It then has a better throughput than a "regular" SSD that typically offers around 500MB/s throughput.
However, this typically only happens when running on a EC2 cloud instance in the same region as the s3 bucket.
See https://docs.atoti.io/0.4.1/data-access.html#cloud-object-stores

When running on a local machine, the bandwidth to the s3 bucket is much smaller (100MB/s is already a pretty good number) and it then becomes more interesting to download the data from the s3 bucket once and cache it on the local machine.

We need to think whether we automatically want to perform this "optimization", and what the impacts may be (e.g. the disk space requirement on the local machine).

**Comment by fabiencelier** [comment] 2020-11-12 14:03
This should be fixed in next release: since https://github.com/activeviam/atoti/pull/1633 we cache cloud files locally

**Closed** 2020-12-08 15:48 UTC
Labels: bug :bug:, question :question:
