### ISSUE TITLE
Broken MDX query after a few steps

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#687] opened 2022-09-14 07:48 UTC
## Steps to reproduce
1) Run the following notebook (https://drive.google.com/drive/folders/1EVZ96VeAjLsKpKfxMpldy6oCa3WABH8V?usp=sharing) to the last cell (which is a pivot table).
2) Expand the multi-level hierarchy on COLUMNS by Months.
3) You get an error: Duplicates: [MonthKey, MonthKey, Reporting_CurrencyKey, Flows_to_Accounts Tree/Level 3, Value]
Try to undo or refresh the page. (TBC with you, this may be another issue/ticket)
4) Remove this Years/Quarters/Months hierarchy from the ContentEditor.
5) Add it back to COLUMNS and expend only by Quarters.
6) Add the contributors.COUNT => it does not work.
7) Remove everything (measures, hierarchies and filters) from the ContentEditor, the MDX query still (and should not) contain this: `SELECT Hierarchize({[Measures].[Value.SUM]}) ON COLUMNS FROM [Flows] CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS`

## Actual Result
A measure is not removed from the MDX query, and not any measure can be added from this step ; the widget need to be recreated, which is painful from a notebook.

## Expected Result
Add multi-level hierarchies on ROWS and COLUMNS and measures on COLUMNS without issue.

## Environment
atoti-plus 0.7.0

**Comment by tibdex** [comment] 2022-09-14 18:30
Hi Harold, can you confirm that you get the same problem when using the app and not the JupyterLab extension?

**Comment by Harold7665** [comment] 2022-09-15 06:50
Yes.
You can copy this bad query and try to add a new measure:
```
SELECT
  NON EMPTY Hierarchize(
    Union(
      Crossjoin(
        Hierarchize(
          {
            [Measures].[Value.SUM]
          }
        ),
        Hierarchize(
          Descendants(
            {
              [Times].[Time].[AllMember]
            },
            1,
            SELF_AND_BEFORE
          )
        )
      ),
      Crossjoin(
        [Measures].[Value.SUM],
        Descendants(
          {
            [Times].[Time].[AllMember].[2020]
          },
          [Times].[Time].[Quarters]
        )
      )
    )
  ) ON COLUMNS,
  NON EMPTY Hierarchize(
    Union(
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember]
        },
        1,
        SELF_AND_BEFORE
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[1]
        },
        [Accounts Tree].[Account Tree].[Level 2]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[1].[10]
        },
        [Accounts Tree].[Account Tree].[Level 3]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[1].[10].[100]
        },
        [Accounts Tree].[Account Tree].[Level 4]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[1].[10].[100].[1000]
        },
        [Accounts Tree].[Account Tree].[Level 5]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[1].[10].[100].[1200]
        },
        [Accounts Tree].[Account Tree].[Level 5]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[2]
        },
        [Accounts Tree].[Account Tree].[Level 2]
      ),
      Descendants(
        {
          [Accounts Tree].[Account Tree].[AllMember].[2].[30]
        },
        [Accounts Tree].[Account Tree].[Level 3]
      )
    )
  ) ON ROWS
  FROM (
    SELECT
    [Times].[Time].[AllMember].[2020].[2020Q1] ON COLUMNS
    FROM [Flows]
  )
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
```

**Comment by Harold7665** [comment] 2022-09-20 12:34
I have reproduced with Excel, so it seems to be a core bug also..

**Comment by bloussou** [comment] 2022-09-20 12:52
If I replace `l["MonthKey"]` by `l["Months"]` I cannot reproduce the issue, both levels are pointing to the table column `MonthKey` and used alternatively in the notebook. I don't think it is a clean way to proceed and therefore this `Duplicates: [MonthKey, MonthKey, Reporting_CurrencyKey, Flows_to_Accounts Tree/Level 3, Value]` is probably justified... Not sure I'm working on a reproduction with a simpler code

**Comment by Harold7665** [comment] 2022-09-21 07:15
Hello,
I have tried this and now I get a `Cannot read 'double' value from an instance of EmptyChunk`.
Here are the logs: [server.zip](https://github.com/atoti/atoti/files/9613960/server.zip)

**Comment by bloussou** [comment] 2022-11-03 14:10
I'm closing this as the code was wrong (mixing two different levels and expecting these levels to have the same behavior).

**Closed by bloussou** 2022-11-03 14:10 UTC
Labels: :bug: bug, :lipstick: ui, :hourglass_flowing_sand: waiting dependency
