### ISSUE TITLE
Active and Inactive Relationships to Handle Multiple Dates

### ISSUE THREAD

**Issue by ncosgrov58** [atoti/atoti#516] opened 2022-03-10 19:10 UTC
I have a data model with a schema similar to below.  The Sales table has  multiple date for Order and Ship and I would like to do reports on both.  However, when I attempt to add a second relationship between the Sales Table and the Dates Table (something which when you do it in Power BI would create an inactive relationship) it throws an error.  How can I show a table in atoti with this form of multiple relationship and then specify which relationship  should be used in creating a measure.

![image](https://user-images.githubusercontent.com/57536496/157736416-97db6c4e-85e0-4b1a-9750-4baebb7f97ae.png)

**Comment by ncosgrov58** [comment] 2022-03-11 15:14
Note clicking on those links, I am getting a 404 error

**Comment by ncosgrov58** [comment] 2022-03-28 19:12
Any word on a solution or work around?  Again as note the links above throw 404's for me

**Comment by Acriss** [comment] 2022-03-29 07:25
Hey !
Sorry for the delay. The issue behind your problem created a chain of other issues that are getting resolved.
The last message I can see is that it should be working once a final PR is merged.

However, we just released a version of atoti (0.6.5) and I expect we won't be releasing another one soon. (To be confirmed).

The 404's you're seeing are references to a private repository.
Regards,
Acris

**Comment by ncosgrov58** [comment] 2022-03-29 13:15
Thanks for the response.  Is there any known workaround?  All the best

**Comment by tibdex** [comment] 2022-07-13 16:42
Hi Neil, do you still have the issue with atoti 0.6.6?

**Comment by tibdex** [comment] 2023-02-16 20:41
Hi, I'm closing the issue since there's been no answer for a while. Feel free to reopen if needed.

**Closed by tibdex** 2023-02-16 20:41 UTC
