### ISSUE TITLE
AtotiJavaException when loading parquet file with : in column name

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#448] opened 2021-12-29 09:44 UTC
## Steps to reproduce
Load a .parquet file having a column with ':'. A test has been done R&D side where having a ':' in column name breaks tests.

## Actual Result
AtotiJavaException.

## Expected Result
Load parquet file with : in column name as panda does.

## Environment
- atoti: 0.6.4.2968.20211221171448
- Python: 3.10.0
- Operating System: Linux

## Logs
No server logs, only atoti logs.
```
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/envs/wellington-discovery/lib/python3.10/site-packages/atoti/_transaction.py in __exit__(self, exception_type, exception_instance, exception_traceback)
     65         has_succeeded = exception_instance is None
     66         _transaction_id_context.set(None)
---> 67         self._end(has_succeeded=has_succeeded, transaction_id=self._id)

~/miniconda3/envs/wellington-discovery/lib/python3.10/site-packages/atoti/exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     76                 else f"{java_api.get_throwable_root_cause(java_exception.java_exception)}"
     77             )
---> 78             raise AtotiJavaException(
     79                 cause,
     80                 java_traceback=str(java_exception),

AtotiJavaException: Illegal character in: account:acct_id
```

**Comment by bloussou** [comment] 2022-01-03 16:32
Hello,
Thanks for reporting this issue, it is not supported by the core yet I have created an issue : https://support.activeviam.com/jira/browse/PIVOT-5235

**Comment by bloussou** [comment] 2022-01-04 09:59
It cannot be supported by the core. Do you really need this name with `:` ? If not you can change the name in the parquet file before loading it. If yes you can change the name before loading it and then change the name of the hierarchy or measure to go back to the name with `:` in it.
Column name ` cannot contain non alphanumeric characters for now`.

Duplicate of https://github.com/atoti/atoti/issues/242

**Comment by Harold7665** [comment] 2022-01-04 10:05
Hello,
No I do not really need it. I have created the ticket as it was supported by pandas but not by atoti.
Thanks!

**Closed** 2022-07-13 16:43 UTC
Labels: :bug: bug, :hourglass_flowing_sand: waiting dependency
