### ISSUE TITLE
File permissions : ExitCodeException exitCode=-1073741515

### ISSUE THREAD

**Issue by ncosgrov58** [atoti/atoti#323] opened 2021-07-26 22:08 UTC
## Steps to reproduce

Attempting to read a dataframe into the session in 0.6.0

```python
table = session.read_pandas(df, table_name="Data")
```

## Actual Result
Receive following error

```
AtotiJavaException: Error while running command to get file permissions : ExitCodeException exitCode=-1073741515: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:998)
	at org.apache.hadoop.util.Shell.run(Shell.java:884)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1216)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:1310)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:1292)
	at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1118)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.loadPermissionInfo(RawLocalFileSystem.java:693)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.getPermission(RawLocalFileSystem.java:668)
	at org.apache.hadoop.fs.LocatedFileStatus.<init>(LocatedFileStatus.java:47)
	at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:2033)
	at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:2013)
	at org.apache.hadoop.fs.FileSystem$5.hasNext(FileSystem.java:2131)
	at com.activeviam.parquet.impl.ParquetParser$RemoteStandardIterator.hasNext(ParquetParser.java:1011)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.activeviam.parquet.impl.ParquetParser.parse(ParquetParser.java:524)
	at io.atoti.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:73)
	at io.atoti.loading.parquet.visitor.ParquetParserPathVisitor.visit(ParquetParserPathVisitor.java:32)
	at io.atoti.util.files.LocalPath.accept(LocalPath.java:186)
	at io.atoti.loading.parquet.impl.ParquetDataTable.loadPathWithinTransaction(ParquetDataTable.java:131)
	at io.atoti.loading.impl.AFileBasedDataTable.loadWithinTransaction(AFileBasedDataTable.java:54)
	at io.atoti.loading.impl.DataTableOperationUnit.executeOperation(DataTableOperationUnit.java:21)
	at io.atoti.loading.impl.AtotiStore.lambda$loadData$23(AtotiStore.java:863)
	at com.qfs.store.transaction.impl.TransactionManager.performInTransaction(TransactionManager.java:2708)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.performInTransaction(FlexibleTransactionManager.java:207)
	at io.atoti.loading.impl.AtotiStore.loadData(AtotiStore.java:860)
	at io.atoti.loading.impl.ADataTable.registerToStore(ADataTable.java:46)
	at io.atoti.loading.DataTableManager.addNewDataTable(DataTableManager.java:32)
	at io.atoti.loading.impl.DataLoaderImpl.lambda$loadSource$0(DataLoaderImpl.java:66)
	at java.base/java.util.Collections$SingletonSet.forEach(Unknown Source)
	at io.atoti.loading.impl.DataLoaderImpl.loadSource(DataLoaderImpl.java:66)
	at io.atoti.api.impl.OutsideTransactionAtotiApi.createStoreFromDataSource(OutsideTransactionAtotiApi.java:125)
	at io.atoti.api.impl.AtotiApiImpl.createStoreFromDataSource(AtotiApiImpl.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Unknown Source)
```

## Environment
atoti: 0.6
python: 3.9.6
Operating system:  OS Name: Microsoft Windows Server 2019 Datacenter
OS Version: 10.0.17763 N/A Build 17763

**Comment by rcolle** [comment] 2021-07-27 04:01
This may be the cause:
https://github.com/steveloughran/winutils/issues/7

@ncosgrov58 can you try the suggested workaround in the issue above?

@atoti/rnd if this is the issue, could we try to catch and explain this exception?

**Comment by ncosgrov58** [comment] 2021-07-27 04:26
Unfortunately, the fix suggested has links to  to downloads that are no longer available

**Comment by rcolle** [comment] 2021-07-27 13:24
It looks like there were moved there:
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by ncosgrov** [comment] 2021-07-27 13:52
No joy. Installed the packages, did a system restart, same error.

**Comment by ncosgrov58** [comment] 2021-07-27 17:16
By wat of followup: I actually brought up a ne virtual machine and started from scratch, have wounded up with same error.

**Comment by rcolle** [comment] 2021-07-28 12:46
It's very weird because I've never had this issue on our own Windows installations, but it turns out that we've ran into it for our Windows CI machines (we're using CircleCI).

We've tried several existing binaries but they did not seem to work. @tibdex had to crawl the internet archives to find a working binary. Please find below the one that we installed on our CI (running `vcredist_x64.exe` from the zipped file).

DISCLAIMER: WE PROVIDE NO WARRANTY FOR THE BINARY FILE BELOW. USE IT AT YOU OWN RISK
[vcredist_x64.zip](https://github.com/atoti/atoti/files/6893091/vcredist_x64.zip)

**Comment by tibdex** [comment] 2021-07-28 13:10
> It's very weird because I've never had this issue on our own Windows installations, but it turns out that we've ran into it for our Windows CI machines (we're using CircleCI).

[CircleCI's Windows executor is using Windows Server 2019](https://circleci.com/docs/2.0/hello-world-windows/#overview-of-the-windows-executor) so maybe it's a Microsoft Windows **Server** specific thing 🤔.

**Comment by ncosgrov58** [comment] 2021-07-28 13:50
OK, that worked.  Note that I am also using Window Server 2019 but on Azure, so the Window Server 2019 would seem to be the suspect

**Comment by bloussou** [comment] 2022-01-27 10:38
I'm closing this as it is resolved

**Closed by bloussou** 2022-01-27 10:38 UTC
Labels: :bug: bug
