### ISSUE TITLE
Hierarchies with numerical values got concatenated in x-axis

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#247] opened 2021-02-22 06:49 UTC
## Steps to reproduce

I have hours on the x-axis:
![image](https://user-images.githubusercontent.com/35210495/108671904-2712a700-751c-11eb-9b36-b560f8a667bf.png)

I wanted to split it further with another numerical hierarchy called "dayofweek":
![image](https://user-images.githubusercontent.com/35210495/108671992-46113900-751c-11eb-9f5e-9fc11f4999f8.png)

The x-axis values no longer make sense. 

In this use case, I'm pulling data from mySQL and the data type is INT. 
I cannot set type to STRING either:
```
consumption = session.read_sql(
    "jdbc:mysql://localhost:3306/atoti",
    "SELECT * FROM atoti.consumption;",
    username="",
    password="",
    store_name="consumption",
    keys=["id"],
    types={
        "hour": tt.type.STRING,
        "dayofweek": tt.type.STRING,
        "dayofmonth": tt.type.STRING,
        "quarter": tt.type.STRING,
        "month": tt.type.STRING,
        "year": tt.type.STRING,
    },
)
```
It will give me exceptions:
<details><pre>
Feb 22, 2021 2:48:18 PM com.qfs.msg.jdbc.impl.AJDBCSource$JDBCTask call
INFO: JDBC Source Columns: id (java.lang.Integer), smart_id (java.lang.String), max_power (java.lang.Float), consumption (java.lang.Float), ds (java.sql.Timestamp), hour (java.lang.Integer), dayofweek (java.lang.Integer), quarter (java.lang.Integer), month (java.lang.Integer), dayofmonth (java.lang.Integer), year (java.lang.Integer)
Feb 22, 2021 2:48:18 PM io.atoti.util.impl.AtotiGlobalExceptionHandler uncaughtException
SEVERE: Uncaught exception in thread Thread-10
java.lang.ClassCastException: Incorrect type Integer for tuple with value 17 for lookup in dictionary of type NullableDictionary. Exception in store: consumption, field: hour, for tuple: [1, ID_1, 63.094, 29.313, 2017-11-15 17:00:00.0, 17, 2, 4, 11, 15, 2017].
	at com.qfs.store.transaction.impl.TransactionManager.transformToFullRecords(TransactionManager.java:1365)
	at com.qfs.store.transaction.impl.TransactionManager.addAll(TransactionManager.java:1123)
	at com.qfs.store.transaction.ITransactionalWriter.addAll(ITransactionalWriter.java:117)
	at com.qfs.store.transaction.impl.FlexibleTransactionManager.addAll(FlexibleTransactionManager.java:250)
	at com.qfs.source.impl.TuplePublisher.publish(TuplePublisher.java:119)
	at com.qfs.source.impl.StoreMessage.append(StoreMessage.java:119)
	at com.qfs.msg.jdbc.impl.AJDBCSource$JDBCAppendRunnable.run(AJDBCSource.java:620)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
		at com.qfs.dic.impl.ChristmasDictionary$ChristmasDictionaryString.map(ChristmasDictionary.java:108)
		at com.qfs.dic.impl.NullableDictionary.map(NullableDictionary.java:177)
		at com.qfs.store.transaction.impl.TransactionManager.transformToFullRecords(TransactionManager.java:1336)
		... 7 more
</pre></details>

If I change the DB type to VARCHAR, the plot is also wrong:
![image](https://user-images.githubusercontent.com/35210495/108673384-8671b680-751e-11eb-8da4-9df04775399f.png)

## Expected Result
I'm expecting the x-axis to be comma separated like below:
![1_J2YSUqi1IWJAjJsjXfhNTg](https://user-images.githubusercontent.com/35210495/108672670-760d0c00-751d-11eb-80ec-6e5b6b95d6fb.gif)

## Environment
- atoti: 0.5.1
- Operating System: win32

**Comment by HuifangYeo** [comment] 2021-02-22 07:06
Just discovered that it will display nicely if I drag the `Measures` tile from Split section into the x-axis section:
![image](https://user-images.githubusercontent.com/35210495/108673897-67bfef80-751f-11eb-9772-51eb7daf512c.png)

However, this is not very intuitive.

**Comment by tibdex** [comment] 2021-02-22 07:50
Hi Hui Fang, can you share the notebook and its data to help us reproduce this easily?

**Comment by HuifangYeo** [comment] 2021-02-22 08:04
Hi @tibdex,

please see the csv version of the noteboook.
[energy.zip](https://github.com/atoti/atoti/files/6020411/energy.zip)

**Comment by AlexVernet** [comment] 2021-02-23 10:19
I've created an [internal ticket](https://support.activeviam.com/jira/browse/UI-5388) for the UI team about this issue.

**Comment by bloussou** [comment] 2022-01-27 15:21
The issue is still here in `0.6.4` and AUI `5.0.7`

**Comment by tibdex** [comment] 2022-07-05 14:18
Closing this as the internal ticket got postponed.

**Closed by tibdex** 2022-07-05 14:18 UTC
Labels: :bug: bug, :lipstick: ui, :calendar: postponed
