### ISSUE TITLE
KeyError: DataType(null)

### ISSUE THREAD

**Issue by tibdex** [atoti/atoti#484] opened 2022-02-28 13:41 UTC
### Discussed in https://github.com/atoti/atoti/discussions/483

<div type='discussions-op-text'>

<sup>Originally posted by **Mano251290** February 28, 2022</sup>
When I am trying to create a store , using `read_pandas()`

```py 
instrument_store = session.read_pandas(df_instrument , table_name='Instruments',keys=['INSTRUMENT_ID',])
```

I am always getting the `KeyError: DataType(null)`. The Key column is present in the df, still getting the error.

Full error:

```
KeyError Traceback (most recent call last)
/tmp/ipykernel_5156/2174399869.py in <module>
----> 1 instrument_store = session.read_pandas(df_instrument , table_name='Instruments',keys=['INSTRUMENT_ID',])
2 instrument_cube = session.create_cube(instrument_store,name='Instruments')

~/.local/lib/python3.7/site-packages/atoti/_telemetry.py in function_wrapper(args, **kwargs)
220
221 try:
--> 222 return _track_call(function, call_path, args, **kwargs)
223 finally:
224 call_tracker.tracking = False

~/.local/lib/python3.7/site-packages/atoti/_telemetry.py in _track_call(function, call_path, args, *kwargs)
183 # Do nothing to let the previous error be the one presented to the user.
184 ...
--> 185 raise error
186 finally:
187 arguments: Dict[str, str] = {}

~/.local/lib/python3.7/site-packages/atoti/_telemetry.py in _track_call(function, call_path, args, **kwargs)
176 call_time = time.perf_counter()
177 try:
--> 178 return function(args, **kwargs)
179 except Exception as error: # pylint: disable=broad-except
180 try:

~/.local/lib/python3.7/site-packages/atoti/_runtime_type_checking_utils.py in typechecked_func_wrapper(args, **kwargs)
183
184 # Call the actual function.
--> 185 return self._func(args, **kwargs)
186
187 # Mark the function as typechecked and return it.

~/.local/lib/python3.7/site-packages/atoti_core/doc.py in wrapper(args, **kwargs)
19 @wraps(function)
20 def wrapper(args: _P.args, kwargs: _P.kwargs) -> Any:
---> 21 return function(*args, kwargs)
22
23 # Collecting docstring and docstring templates

~/.local/lib/python3.7/site-packages/atoti/session.py in read_pandas(self, dataframe, table_name, keys, partitioning, types, hierarchized_columns, kwargs)
202 types=types,
203 hierarchized_columns=hierarchized_columns,
--> 204 kwargs,
205 )
206

~/.local/lib/python3.7/site-packages/atoti/session.py in _read_arrow(self, arrow_table, table_name, keys, partitioning, types, hierarchized_columns, kwargs)
218 types_from_arrow = get_data_types_from_arrow(
219 arrow_table,
--> 220 keys=keys,
221 )
222 types = {types_from_arrow, **types} if types is not None else types_from_arrow

~/.local/lib/python3.7/site-packages/atoti/_arrow_utils.py in get_data_types_from_arrow(table, keys)
74 and (table.column_names[i] not in keys),
75 )
---> 76 for i, arrow_type in enumerate(arrow_types)
77 }
78

~/.local/lib/python3.7/site-packages/atoti/_arrow_utils.py in <dictcomp>(.0)
74 and (table.column_names[i] not in keys),
75 )
---> 76 for i, arrow_type in enumerate(arrow_types)
77 }
78

KeyError: DataType(null)
```</div>

**Comment by bloussou** [comment] 2022-02-28 15:10
Hello,
@Mano251290 can you share `df_instrument.dtypes` and `df_instrument.index` to help us reproduce the issue ?

**Comment by bloussou** [comment] 2022-04-01 14:43
Looks similar to #547

**Comment by bloussou** [comment] 2022-05-11 13:25
I'm closing this since there is no update and it looks similar to #547, @Mano251290 feel free to reopen it with a reproducible example if you are still facing the issue.

**Closed by bloussou** 2022-05-11 13:25 UTC
Labels: :bug: bug
